#!/usr/local/bin/perl

#open file containing blank lines and print it
#where all double letters are inside ()
#count only those lines containing double letters

$buff = '/usr/u/jctstaff/danzig/electricity.txt';
open(INFO, $buff);

$a = 0;
while ($_ = <INFO>)
{
    if(s/([a-zA-Z])\1/(\1\1)/g){ 
	    printf("%l03d ", ++$a);
	    print $_;
}
	else{
	    printf("    %s", $_);}
}

close(INFO);















